// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: internal/protos/todo.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTodosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodosRequest) Reset() {
	*x = GetTodosRequest{}
	mi := &file_internal_protos_todo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodosRequest) ProtoMessage() {}

func (x *GetTodosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_todo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodosRequest.ProtoReflect.Descriptor instead.
func (*GetTodosRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_todo_proto_rawDescGZIP(), []int{0}
}

type TodoItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodoItem) Reset() {
	*x = TodoItem{}
	mi := &file_internal_protos_todo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoItem) ProtoMessage() {}

func (x *TodoItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_todo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoItem.ProtoReflect.Descriptor instead.
func (*TodoItem) Descriptor() ([]byte, []int) {
	return file_internal_protos_todo_proto_rawDescGZIP(), []int{1}
}

func (x *TodoItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TodoItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type TodoItems struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TodoItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodoItems) Reset() {
	*x = TodoItems{}
	mi := &file_internal_protos_todo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodoItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoItems) ProtoMessage() {}

func (x *TodoItems) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_todo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoItems.ProtoReflect.Descriptor instead.
func (*TodoItems) Descriptor() ([]byte, []int) {
	return file_internal_protos_todo_proto_rawDescGZIP(), []int{2}
}

func (x *TodoItems) GetItems() []*TodoItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_internal_protos_todo_proto protoreflect.FileDescriptor

const file_internal_protos_todo_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/protos/todo.proto\x12\x04todo\"\x11\n" +
	"\x0fGetTodosRequest\"B\n" +
	"\bTodoItem\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"1\n" +
	"\tTodoItems\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.todo.TodoItemR\x05items2g\n" +
	"\x04Todo\x12,\n" +
	"\n" +
	"CreateTodo\x12\x0e.todo.TodoItem\x1a\x0e.todo.TodoItem\x121\n" +
	"\aGetTodo\x12\x15.todo.GetTodosRequest\x1a\x0f.todo.TodoItemsB\rZ\vtodo/protosb\x06proto3"

var (
	file_internal_protos_todo_proto_rawDescOnce sync.Once
	file_internal_protos_todo_proto_rawDescData []byte
)

func file_internal_protos_todo_proto_rawDescGZIP() []byte {
	file_internal_protos_todo_proto_rawDescOnce.Do(func() {
		file_internal_protos_todo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protos_todo_proto_rawDesc), len(file_internal_protos_todo_proto_rawDesc)))
	})
	return file_internal_protos_todo_proto_rawDescData
}

var file_internal_protos_todo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_protos_todo_proto_goTypes = []any{
	(*GetTodosRequest)(nil), // 0: todo.GetTodosRequest
	(*TodoItem)(nil),        // 1: todo.TodoItem
	(*TodoItems)(nil),       // 2: todo.TodoItems
}
var file_internal_protos_todo_proto_depIdxs = []int32{
	1, // 0: todo.TodoItems.items:type_name -> todo.TodoItem
	1, // 1: todo.Todo.CreateTodo:input_type -> todo.TodoItem
	0, // 2: todo.Todo.GetTodo:input_type -> todo.GetTodosRequest
	1, // 3: todo.Todo.CreateTodo:output_type -> todo.TodoItem
	2, // 4: todo.Todo.GetTodo:output_type -> todo.TodoItems
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_protos_todo_proto_init() }
func file_internal_protos_todo_proto_init() {
	if File_internal_protos_todo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protos_todo_proto_rawDesc), len(file_internal_protos_todo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protos_todo_proto_goTypes,
		DependencyIndexes: file_internal_protos_todo_proto_depIdxs,
		MessageInfos:      file_internal_protos_todo_proto_msgTypes,
	}.Build()
	File_internal_protos_todo_proto = out.File
	file_internal_protos_todo_proto_goTypes = nil
	file_internal_protos_todo_proto_depIdxs = nil
}
